### ISSUE TITLE
Add User Stories to Readme

### ISSUE THREAD

**Issue by rbaset5** [DTLivingstone/portfolio#11]
I would add user stories and developer stories to your readme. This will give you a better long term vision as a developer and help you develop in a user centered approach. Think about what you as a user want as they visit your site on a macro and micro level. This can also give you ideas on features to implement that are beneficial to the user and make their visit more pleasant. Adding developer stories will allow you to think about things you want to avoid and consider while further writing out your code base.

**Comment by DTLivingstone** [comment]
I added these to the bottom of the readme.
