### ISSUE TITLE
Re-position Project Descriptions 

### ISSUE THREAD

**Issue by rbaset5** [DTLivingstone/portfolio#9]
I like how you have a screenshot of the project you worked on so the user can see the site without having to click on a link. Including your descriptions parallel to your screenshot would be beneficial in that the user can read the description while having a full view of the screenshot as opposed to a partial view. Increasing the size of your description text will also eliminate some of the white space you have next to the images.

**Comment by DTLivingstone** [comment]
I've completed this, but now I need to add padding.
